---
plugin: gcp_compute
projects:
  - otus-262520
zones:
  - "us-central1-a"
filters: []
auth_kind: serviceaccount
service_account_file: "./OTUS-e62f494b21b3.json"
groups:
  app: "'-app' in name"
  db: "'-db' in name"
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  internal_ip: networkInterfaces[0].networkIP
strict: true
